services:
  - type: web
    name: bookstore-web
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BASE_URL
        value: /
      - key: DB_HOST
        value: mysql-242c21d4-khanhhoan121209-543d.j.aivencloud.com
      - key: DB_PORT
        value: "12799"
      - key: DB_USER
        value: avnadmin
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: defaultdb
